"use strict";

const { contextBridge, ipcRenderer } = require("electron");

// Do not forward the ErrorEvent, rejected value, DOM node or resource URL.
const recordProblem = code => { void ipcRenderer.invoke("grey-crow:record-renderer-problem", { code }).catch(() => {}); };
window.addEventListener("error", event => recordProblem(event.target === window ? "RENDERER_SCRIPT_ERROR" : "RENDERER_RESOURCE_ERROR"), true);
window.addEventListener("unhandledrejection", () => recordProblem("RENDERER_PROMISE_ERROR"));

const CHANNELS = Object.freeze({
  QUIT_APP: "grey-crow:quit-app",
  GET_STATUS: "grey-crow:get-status",
  GET_SETTINGS: "grey-crow:get-settings",
  GET_TUTORIAL_PROGRESS: "grey-crow:get-tutorial-progress",
  SET_TUTORIAL_DISMISSED: "grey-crow:set-tutorial-dismissed",
  UPDATE_SETTINGS: "grey-crow:update-settings",
  LIST_SAVE_SLOTS: "grey-crow:list-save-slots",



  OPEN_STORY_ARCHIVE: "grey-crow:open-story-archive",
  EXPORT_STORY_ARCHIVE: "grey-crow:export-story-archive",
  CONTINUE_STORY_ARCHIVE: "grey-crow:continue-story-archive",
  TEST_PROVIDER_CONNECTION: "grey-crow:test-provider-connection",
  UPSERT_CUSTOM_CONNECTION: "grey-crow:upsert-custom-connection",
  DELETE_CUSTOM_CONNECTION: "grey-crow:delete-custom-connection",
  CLEAR_PROVIDER_CREDENTIAL: "grey-crow:clear-provider-credential",
  CLEAR_ALL_PROVIDER_CREDENTIALS: "grey-crow:clear-all-provider-credentials",
  OPEN_MODEL_HELP: "grey-crow:open-model-help",
  LIST_CONTENT_LIBRARY: "grey-crow:list-content-library",
  CLONE_CONTENT_PACK: "grey-crow:clone-content-pack",
  CREATE_BLANK_CONTENT: "grey-crow:create-blank-content",
  EXPORT_CONTENT_PACK: "grey-crow:export-content-pack",
  DELETE_CONTENT_PACK: "grey-crow:delete-content-pack",
  LOAD_EDITABLE_CONTENT: "grey-crow:load-editable-content",
  SAVE_EDITABLE_CONTENT: "grey-crow:save-editable-content",
  SAVE_CONTENT_PRESET: "grey-crow:save-content-preset",
  PREVIEW_SKILL_MODULE: "grey-crow:preview-skill-module",
  GET_PLAYER_PROFILE: "grey-crow:get-player-profile",
  SAVE_PLAYER_PROFILE: "grey-crow:save-player-profile",
  START_NEW_GAME: "grey-crow:start-new-game",
  GET_NEW_GAME_CATALOG: "grey-crow:get-new-game-catalog",
  PREPARE_NEW_GAME: "grey-crow:prepare-new-game",
  CONFIRM_NEW_GAME_CREATION: "grey-crow:confirm-new-game-creation",
  REQUEST_NEW_GAME_RESTART: "grey-crow:request-new-game-restart",
  CONFIRM_NEW_GAME_RESTART: "grey-crow:confirm-new-game-restart",
  CONTINUE_GAME: "grey-crow:continue-game",
  LIST_SKILL_MODULES: "grey-crow:list-skill-modules",
  GET_SKILL_MODULE: "grey-crow:get-skill-module",
  LIST_SKILL_PANELS: "grey-crow:list-skill-panels",
  GET_CHARACTER_PANEL_ENTRY: "grey-crow:get-character-panel-entry",
  GET_SKILL_PANEL: "grey-crow:get-skill-panel",
  REQUEST_SAVE_MAINTENANCE: "grey-crow:request-save-maintenance",
  CONFIRM_SAVE_MAINTENANCE: "grey-crow:confirm-save-maintenance",
  REQUEST_CONTEXT_COMPACTION: "grey-crow:request-context-compaction",
  READ_CONTEXT_COMPACTION: "grey-crow:read-context-compaction",
  REQUEST_MANUAL_SAVE: "grey-crow:request-manual-save",
  RESUME_SESSION_FINALE: "grey-crow:resume-session-finale",
  GET_CHAPTER_LOGS: "grey-crow:get-chapter-logs",
  GET_DEBUG_TRACE: "grey-crow:get-debug-trace",
  EXPORT_PROBLEM_REPORT: "grey-crow:export-problem-report",
  SYNTHESIZE_TTS: "grey-crow:synthesize-tts",
  START_TTS_UTTERANCE: "grey-crow:start-tts-utterance",
  CONTINUE_TTS_UTTERANCE: "grey-crow:continue-tts-utterance",
  CANCEL_TTS_UTTERANCE: "grey-crow:cancel-tts-utterance",
  GET_TTS_CACHE_STATUS: "grey-crow:get-tts-cache-status",
  CLEAR_TTS_CACHE: "grey-crow:clear-tts-cache",
  RUN_TURN: "grey-crow:run-turn",
  CANCEL_TURN: "grey-crow:cancel-turn",
  COMPLETE_TURN_DERIVED: "grey-crow:complete-turn-derived",
  READ_SESSION_HISTORY: "grey-crow:read-session-history",
  LEAVE_ADVENTURE: "grey-crow:leave-adventure",
  RESET_SESSION: "grey-crow:reset-session",
});

contextBridge.exposeInMainWorld("greyCrow", {
  quitApp: () => ipcRenderer.invoke(CHANNELS.QUIT_APP),
  getStatus: () => ipcRenderer.invoke(CHANNELS.GET_STATUS),
  getSettings: () => ipcRenderer.invoke(CHANNELS.GET_SETTINGS),
  getTutorialProgress: (topic = "intro") => ipcRenderer.invoke(CHANNELS.GET_TUTORIAL_PROGRESS, { topic }),
  setTutorialDismissed: (dismissed, topic = "intro") => ipcRenderer.invoke(CHANNELS.SET_TUTORIAL_DISMISSED, { dismissed, topic }),
  updateSettings: (settings) => ipcRenderer.invoke(CHANNELS.UPDATE_SETTINGS, { settings }),
  listSaveSlots: () => ipcRenderer.invoke(CHANNELS.LIST_SAVE_SLOTS),
  openStoryArchive: (saveId) => ipcRenderer.invoke(CHANNELS.OPEN_STORY_ARCHIVE, { saveId }),
  exportStoryArchive: (format, options = {}) => ipcRenderer.invoke(CHANNELS.EXPORT_STORY_ARCHIVE, { format,
    ...(options.adventureId === undefined ? {} : { adventureId: options.adventureId }),
    ...(options.sessionId === undefined ? {} : { sessionId: options.sessionId }),
    ...(options.revision === undefined ? {} : { revision: options.revision }) }),
  continueStoryArchive: (request = {}) => ipcRenderer.invoke(CHANNELS.CONTINUE_STORY_ARCHIVE, {
    ...(request.adventureId === undefined ? {} : { adventureId: request.adventureId }),
    ...(request.sessionId === undefined ? {} : { sessionId: request.sessionId }),
    ...(request.revision === undefined ? {} : { revision: request.revision }),
    ...(request.requestId === undefined ? {} : { requestId: request.requestId }),
    ...(request.sourceFinaleId === undefined ? {} : { sourceFinaleId: request.sourceFinaleId }),
  }),
  testProviderConnection: (payload) => ipcRenderer.invoke(CHANNELS.TEST_PROVIDER_CONNECTION, payload),
  upsertCustomConnection: (connection) => ipcRenderer.invoke(CHANNELS.UPSERT_CUSTOM_CONNECTION, { connection }),
  deleteCustomConnection: (connectionId) => ipcRenderer.invoke(CHANNELS.DELETE_CUSTOM_CONNECTION, { connectionId }),
  clearProviderCredential: (identity = null) => ipcRenderer.invoke(CHANNELS.CLEAR_PROVIDER_CREDENTIAL,
    identity && typeof identity === "object" ? identity : { connectionId: identity }),
  clearAllProviderCredentials: (payload) => ipcRenderer.invoke(CHANNELS.CLEAR_ALL_PROVIDER_CREDENTIALS, payload),
  openModelHelp: (helpId) => ipcRenderer.invoke(CHANNELS.OPEN_MODEL_HELP, { helpId }),
  listContentLibrary: () => ipcRenderer.invoke(CHANNELS.LIST_CONTENT_LIBRARY),
  cloneContentPack: (input) => ipcRenderer.invoke(CHANNELS.CLONE_CONTENT_PACK, input),
  createBlankContent: (input) => ipcRenderer.invoke(CHANNELS.CREATE_BLANK_CONTENT, input),
  exportContentPack: (packId) => ipcRenderer.invoke(CHANNELS.EXPORT_CONTENT_PACK, { packId }),
  deleteContentPack: (packId) => ipcRenderer.invoke(CHANNELS.DELETE_CONTENT_PACK, { packId }),
  loadEditableContent: (packId, itemId) => ipcRenderer.invoke(CHANNELS.LOAD_EDITABLE_CONTENT, { packId, itemId }),
  saveEditableContent: (item) => ipcRenderer.invoke(CHANNELS.SAVE_EDITABLE_CONTENT, item),
  saveContentPreset: (preset) => ipcRenderer.invoke(CHANNELS.SAVE_CONTENT_PRESET, preset),
  previewSkillModule: (draft) => ipcRenderer.invoke(CHANNELS.PREVIEW_SKILL_MODULE, draft),
  getPlayerProfile: () => ipcRenderer.invoke(CHANNELS.GET_PLAYER_PROFILE),
  savePlayerProfile: (fields) => ipcRenderer.invoke(CHANNELS.SAVE_PLAYER_PROFILE, { fields }),
  startNewGame: () => ipcRenderer.invoke(CHANNELS.START_NEW_GAME),
  getNewGameCatalog: () => ipcRenderer.invoke(CHANNELS.GET_NEW_GAME_CATALOG),
  prepareNewGame: (selection) => ipcRenderer.invoke(CHANNELS.PREPARE_NEW_GAME, { selection }),
  confirmNewGameCreation: (confirmationToken) => ipcRenderer.invoke(CHANNELS.CONFIRM_NEW_GAME_CREATION, { confirmationToken }),
  requestNewGameRestart: (saveId) => ipcRenderer.invoke(CHANNELS.REQUEST_NEW_GAME_RESTART, { saveId }),
  confirmNewGameRestart: (saveId, confirmationToken, confirmationText) => ipcRenderer.invoke(CHANNELS.CONFIRM_NEW_GAME_RESTART, {
    saveId,
    confirmationToken,
    confirmationText,
  }),
  continueGame: (saveId) => ipcRenderer.invoke(CHANNELS.CONTINUE_GAME, { saveId }),
  listSkillModules: () => ipcRenderer.invoke(CHANNELS.LIST_SKILL_MODULES),
  getSkillModule: (moduleRef, options = {}) => ipcRenderer.invoke(CHANNELS.GET_SKILL_MODULE, {
    moduleRef,
    fieldId: options.fieldId,
    cursor: options.cursor,
    limit: options.limit,
  }),
  listSkillPanels: () => ipcRenderer.invoke(CHANNELS.LIST_SKILL_PANELS),
  getCharacterPanelEntry: () => ipcRenderer.invoke(CHANNELS.GET_CHARACTER_PANEL_ENTRY),
  getSkillPanel: (panelRef, options = {}) => ipcRenderer.invoke(CHANNELS.GET_SKILL_PANEL, {
    panelRef,
    view: options.view,
    fieldId: options.fieldId,
    itemRef: options.itemRef,
    cursor: options.cursor,
    limit: options.limit,
  }),
  requestSaveMaintenance: (action, options = {}) => ipcRenderer.invoke(CHANNELS.REQUEST_SAVE_MAINTENANCE, {
    action,
    saveId: options.saveId,
    deletionId: options.deletionId,
    compatibilityDelete: options.compatibilityDelete === true,
  }),
  confirmSaveMaintenance: (confirmationToken, confirmationText) => ipcRenderer.invoke(CHANNELS.CONFIRM_SAVE_MAINTENANCE, {
    confirmationToken,
    confirmationText,
  }),
  requestContextCompaction: (payload) => ipcRenderer.invoke(CHANNELS.REQUEST_CONTEXT_COMPACTION, payload),
  readContextCompaction: (payload) => ipcRenderer.invoke(CHANNELS.READ_CONTEXT_COMPACTION, payload),
  requestManualSave: (options = {}) => ipcRenderer.invoke(CHANNELS.REQUEST_MANUAL_SAVE, options),
  resumeSessionFinale: (options = {}) => ipcRenderer.invoke(CHANNELS.RESUME_SESSION_FINALE, options),
  getChapterLogs: (options = {}) => ipcRenderer.invoke(CHANNELS.GET_CHAPTER_LOGS, options),
  getDebugTrace: () => ipcRenderer.invoke(CHANNELS.GET_DEBUG_TRACE),
  exportProblemReport: () => ipcRenderer.invoke(CHANNELS.EXPORT_PROBLEM_REPORT),
  recordProblem: (code) => ipcRenderer.invoke("grey-crow:record-renderer-problem", { code }),
  synthesizeTts: (text) => ipcRenderer.invoke(CHANNELS.SYNTHESIZE_TTS, { text }),
  startTtsUtterance: (text) => ipcRenderer.invoke(CHANNELS.START_TTS_UTTERANCE, { text }),
  continueTtsUtterance: (utteranceId) => ipcRenderer.invoke(CHANNELS.CONTINUE_TTS_UTTERANCE, { utteranceId }),
  cancelTtsUtterance: (utteranceId) => ipcRenderer.invoke(CHANNELS.CANCEL_TTS_UTTERANCE, { utteranceId }),
  getTtsCacheStatus: () => ipcRenderer.invoke(CHANNELS.GET_TTS_CACHE_STATUS),
  clearTtsCache: () => ipcRenderer.invoke(CHANNELS.CLEAR_TTS_CACHE),
  getSpeechInputStatus: () => ipcRenderer.invoke("grey-crow:speech-input-status"),
  installSpeechInputModel: () => ipcRenderer.invoke("grey-crow:speech-input-install"),
  removeSpeechInputModel: () => ipcRenderer.invoke("grey-crow:speech-input-remove"),
  cancelSpeechInput: (options = {}) => ipcRenderer.invoke("grey-crow:speech-input-cancel", { requestId: options.requestId }),
  transcribeSpeechInput: (request = {}) => ipcRenderer.invoke("grey-crow:speech-input-transcribe", {
    requestId: request.requestId, audio: request.audio, adventureId: request.adventureId,
    sessionId: request.sessionId, test: request.test === true,
  }),
  runTurn: (text, options = {}) => ipcRenderer.invoke(CHANNELS.RUN_TURN, { text,
    actionId: options.actionId, baseRevision: options.baseRevision, adventureId: options.adventureId,
    sessionId: options.sessionId, invocationId: options.invocationId, retry: options.retry === true }),
  cancelTurn: (options = {}) => ipcRenderer.invoke(CHANNELS.CANCEL_TURN, {
    actionId: options.actionId, baseRevision: options.baseRevision,
    adventureId: options.adventureId, sessionId: options.sessionId, invocationId: options.invocationId,
  }),
  completeTurnDerived: (work = {}) => ipcRenderer.invoke(CHANNELS.COMPLETE_TURN_DERIVED, {
    ticketId: work.ticketId, actionId: work.actionId, revision: work.revision, kind: work.kind,
    adventureId: work.adventureId, sessionId: work.sessionId,
  }),
  readSessionHistory: (options = {}) => ipcRenderer.invoke(CHANNELS.READ_SESSION_HISTORY, options),
  leaveAdventure: () => ipcRenderer.invoke(CHANNELS.LEAVE_ADVENTURE),
  resetSession: () => ipcRenderer.invoke(CHANNELS.RESET_SESSION),
});
